version: '3.3'

services:

  server:
    build: .
    ports:
      - '6003:22'
    image: gcr.io/i-pivot-325521/speed
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M
