version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:8000'
    image: gcr.io/i-pivot-325521/secure-serializer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: curl --fail http://localhost:8000/alive || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
