version: '3.8'

services:

  server:
    build: .
    ports:
      - '9000:7000'
    image: gcr.io/i-pivot-325521/well-chosen
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: socat - TCP4:localhost:7000 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
