version: '3.8'

services:
  web:
    build: .
    ports:
      - '3003:80'
    image: gcr.io/i-pivot-325521/secret-agent
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: curl --fail http://127.0.0.1/alive || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
